import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, MessageSquare, Cpu, Rocket, LayoutDashboard, CheckCircle, Clock, Zap } from 'lucide-react'
import BookingCTA from '@/components/BookingCTA'

export const metadata: Metadata = {
  title: 'How It Works — Juggernaut Global',
  description:
    'From your first strategy call to your first international sale — a complete walkthrough of how Juggernaut Global takes your Indian D2C brand global in 4 steps.',
  alternates: { canonical: 'https://thejuggernautglobal.com/how-it-works' },
  openGraph: {
    title: 'How It Works — Juggernaut Global',
    description: 'Four steps. 8–12 weeks. Your product selling internationally. Here\'s exactly how.',
    url: 'https://thejuggernautglobal.com/how-it-works',
  },
}

const STEPS = [
  {
    num: '01',
    Icon: MessageSquare,
    title: 'You Tell Us About Your Product',
    subtitle: 'One free 30-minute strategy call.',
    body: [
      'Share your product, category, and where you want to sell. No lengthy onboarding forms — just a focused conversation where we ask exactly the right questions.',
      'We\'ll want to know: what you\'re selling, your current volume in India, any existing certifications, and your target markets. That\'s it.',
      'By the end of the call we\'ll have everything we need to build your expansion plan overnight.',
    ],
    deliverables: [
      'Product suitability assessment',
      'Market shortlist based on your category',
      'Rough compliance complexity estimate',
      'Timeline and next steps',
    ],
    tag: 'One free call',
    timeline: '30 minutes',
  },
  {
    num: '02',
    Icon: Cpu,
    title: 'We Generate Your Complete Expansion Plan',
    subtitle: 'AI-powered analysis delivered in under 24 hours.',
    body: [
      'Our AI analyses your product against 8+ global markets and produces a complete expansion roadmap — no generic advice, no vague suggestions.',
      'The plan covers every market we recommend: compliance requirements by category, estimated compliance cost, capital needed for first shipment, competing products already on each marketplace, expected margin and timeline to first sale.',
      'We rank markets by ROI so you know exactly where to start — and why.',
    ],
    deliverables: [
      'Market-by-market ROI ranking',
      'Complete compliance map per market',
      'Capital and inventory plan',
      'Week-by-week 90-day roadmap',
    ],
    tag: 'Under 24 hours',
    timeline: 'Under 24 hours after call',
  },
  {
    num: '03',
    Icon: Rocket,
    title: 'The Platform Executes. You Approve.',
    subtitle: 'AI-driven execution — with human oversight on every decision.',
    body: [
      'This is where the AI infrastructure activates. Compliance requirements identified in Step 2 are tracked and managed automatically. Listings are generated by AI, optimised for each local marketplace search algorithm, and delivered in the local language.',
      'Our co-founder in Düsseldorf handles what AI cannot — direct compliance filings, local partner relationships, FBA account setup. You get a dashboard view of everything in progress, not a to-do list.',
      'No EU compliance law to learn. No Walmart portal to navigate. No German translation to commission. The infrastructure handles it.',
    ],
    deliverables: [
      'AI-generated, locally-optimised listings',
      'Compliance certifications managed',
      'Marketplace accounts live',
      'FBA / 3PL logistics set up',
      'VAT / tax registered',
      'AI ad campaigns launched',
    ],
    tag: 'AI-driven',
    timeline: 'Weeks 2–10',
  },
  {
    num: '04',
    Icon: LayoutDashboard,
    title: 'You Track Everything. We Keep Optimising.',
    subtitle: 'AI dashboard + ongoing execution. Forever.',
    body: [
      'Once your products are live, your AI dashboard goes live too. Real-time sales across all marketplaces. Compliance status across all markets. Pricing vs competitors. Margin by SKU. Everything in INR and local currency.',
      'We don\'t stop at launch. Our AI continuously monitors listing performance, pricing opportunities, and new marketplace openings. We flag every opportunity — and act on the ones you approve.',
      'Ask our AI chatbot anything about your expansion at any time. It knows your product, your markets, and your performance history.',
    ],
    deliverables: [
      'Live revenue dashboard (INR + local currency)',
      'Compliance status tracker',
      'AI pricing optimisation',
      'Listing A/B testing',
      'Competitor monitoring alerts',
      'AI chatbot — always available',
    ],
    tag: 'Always in control',
    timeline: 'From week 8 onward',
  },
]

export default function HowItWorksPage() {
  return (
    <>
      {/* Hero */}
      <section className="market-hero" style={{ paddingBottom: 64 }}>
        <div className="container">
          <Link href="/" className="back-link">← Home</Link>
          <p className="section-label">The Process</p>
          <h1 className="market-hero-title" style={{ maxWidth: 760 }}>
            Four steps from your warehouse{' '}
            <span className="teal">to the world.</span>
          </h1>
          <p className="market-hero-sub" style={{ maxWidth: 600 }}>
            No guesswork. No months of planning. AI infrastructure that moves fast — from your
            first call to your first international sale, every step automated and tracked.
          </p>
          <div className="market-hero-ctas">
            <Link href="/#book-call" className="btn-primary">
              Start Your Expansion <ArrowRight size={15} />
            </Link>
          </div>
        </div>
      </section>

      {/* Timeline stat strip */}
      <section style={{ background: 'var(--white)', borderBottom: '1px solid var(--border-light)', padding: '32px 6vw' }}>
        <div className="container">
          <div className="stats-strip" style={{ gap: 64 }}>
            {[
              { icon: Clock, label: '30 min', sub: 'First call' },
              { icon: Cpu, label: '24 hrs', sub: 'Expansion plan ready' },
              { icon: Rocket, label: '8–12 wks', sub: 'First international sale' },
              { icon: Zap, label: 'Included', sub: 'AI infrastructure, both models' },
            ].map(({ icon: Icon, label, sub }) => (
              <div key={label} style={{ textAlign: 'center' }}>
                <div style={{
                  width: 56, height: 56, borderRadius: 16,
                  background: 'rgba(12,192,223,0.10)',
                  border: '1px solid rgba(12,192,223,0.18)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  margin: '0 auto 16px',
                }}>
                  <Icon size={28} color="var(--teal)" strokeWidth={1.5} />
                </div>
                <div style={{ fontSize: 22, fontWeight: 800, color: 'var(--text-dark)', fontFamily: 'var(--font-display)' }}>{label}</div>
                <div style={{ fontSize: 13, color: 'var(--text-dim)', marginTop: 4 }}>{sub}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Steps — full detail */}
      {STEPS.map(({ num, Icon, title, subtitle, body, deliverables, tag, timeline }, i) => (
        <section
          key={num}
          className="section section--tight"
          style={{ background: i % 2 === 0 ? 'var(--off-white)' : 'var(--white)' }}
        >
          <div className="container">
            <div style={{
              display: 'grid',
              gridTemplateColumns: '1fr 1fr',
              gap: 80,
              alignItems: 'start',
            }} className="hiw-step-grid">

              {/* Left */}
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 24 }}>
                  <div style={{
                    width: 56, height: 56, borderRadius: 16,
                    background: 'rgba(12,192,223,0.10)',
                    border: '1px solid rgba(12,192,223,0.20)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    flexShrink: 0,
                  }}>
                    <Icon size={26} color="var(--teal)" strokeWidth={1.5} />
                  </div>
                  <span style={{
                    fontSize: 11, fontWeight: 700, letterSpacing: '0.1em',
                    textTransform: 'uppercase', color: 'var(--teal-dark)',
                  }}>
                    Step {num}
                  </span>
                </div>
                <h2 style={{
                  fontFamily: 'var(--font-display)',
                  fontSize: 32, fontWeight: 700, lineHeight: 1.2,
                  color: 'var(--text-dark)', marginBottom: 10,
                }}>
                  {title}
                </h2>
                <p style={{ fontSize: 15, color: 'var(--teal-dark)', fontWeight: 600, marginBottom: 28 }}>
                  {subtitle}
                </p>
                {body.map((p, j) => (
                  <p key={j} style={{ fontSize: 16, lineHeight: 1.75, color: 'var(--text-body)', marginBottom: 16 }}>
                    {p}
                  </p>
                ))}
                <div style={{ display: 'flex', gap: 12, marginTop: 28 }}>
                  <span style={{
                    fontSize: 11, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase',
                    color: 'var(--teal-dark)', background: 'rgba(12,192,223,0.08)',
                    border: '1px solid rgba(12,192,223,0.15)', borderRadius: 4, padding: '5px 12px',
                  }}>
                    {tag}
                  </span>
                  <span style={{
                    fontSize: 11, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase',
                    color: 'var(--text-dim)', background: 'var(--off-white)',
                    border: '1px solid var(--border-light)', borderRadius: 4, padding: '5px 12px',
                  }}>
                    {timeline}
                  </span>
                </div>
              </div>

              {/* Right — deliverables */}
              <div style={{
                background: 'var(--white)',
                border: '1px solid var(--border-light)',
                borderRadius: 20,
                padding: '36px 40px',
                boxShadow: '0 2px 24px rgba(0,0,0,0.04)',
              }}>
                <div style={{
                  fontSize: 11, fontWeight: 700, letterSpacing: '0.10em',
                  textTransform: 'uppercase', color: 'var(--text-dim)', marginBottom: 20,
                }}>
                  What you get from this step
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                  {deliverables.map(d => (
                    <div key={d} style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
                      <CheckCircle size={16} color="var(--teal)" strokeWidth={2} style={{ flexShrink: 0, marginTop: 2 }} />
                      <span style={{ fontSize: 15, color: 'var(--text-body)', lineHeight: 1.5 }}>{d}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>
      ))}

      {/* AI infrastructure strip */}
      <section style={{ background: 'var(--teal-dark)', padding: '52px 6vw' }}>
        <div className="container" style={{ display: 'flex', alignItems: 'center', gap: 24 }}>
          <Zap size={36} color="white" strokeWidth={1.5} style={{ flexShrink: 0 }} />
          <div>
            <div style={{ color: 'white', fontWeight: 700, fontSize: 22, marginBottom: 8 }}>
              AI Infrastructure — the backbone of how we operate. Included on both models.
            </div>
            <p style={{ color: 'rgba(255,255,255,0.75)', fontSize: 15, lineHeight: 1.65, margin: 0 }}>
              Market intelligence · Listing optimisation · Pricing strategy · Compliance monitoring ·
              Live revenue dashboard · AI chatbot. Built for your brand. Zero cost. On both our pricing models.
            </p>
          </div>
        </div>
      </section>

      <BookingCTA />
    </>
  )
}
